server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka,http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

#management:
#  endpoint:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
